### PR TITLE
Implement MDC-using encryption

### PR DESCRIPTION
**Pull request by singpolyma**
In response to https://github.com/singpolyma/openpgp-php/issues/17
In an attempt to close https://github.com/jasonhinkle/php-gpg/issues/18

Code based on https://github.com/singpolyma/openpgp-php

### CODE REVIEW

**Comment by DanielRuf** [comment]
Awesome, thanks. Much apprecited. Will test it tomorrow and merge it then.

@jasonhinkle please check if none of the unittests are broken.

**Comment by DanielRuf** [comment]
It does not work here, `gpg --list-packets` says the file was manipulated:

`gpg: Warnung: Verschlüsselte Botschaft ist manipuliert worden!`

**Comment by singpolyma** [comment]
@DanielRuf Ah yes, there was a bug in the padding handling because of the resync change.  Fixed now.

**Comment by DanielRuf** [comment]
:+1:  great, works here now =)

@jasonhinkle please test on your side. We have to add this also to the dev branch. Should we increment the version to 1.6.0?

**Comment by jasonhinkle** [comment]
Hey @DanielRuf , I don't have a client to test this with - is it possible to write a unit test to verify that it works?

**Comment by DanielRuf** [comment]
> is it possible to write a unit test to verify that it works?

Probably not yet until we have decryption implemented as we have to decrypt, then use the length from the MDC packet and use it to get the prefix and the SHA-1 hash. With this and the decrypted cleartext message we can check if it is correct (hash the cleartext and the prefix and check it with the hash from the decrypted message).

This would be the right way.

**Pull request merged**
